INSERT INTO medication_record (generic_name, brand_name)
VALUES
('Paracetamol', 'Panadol'),
('Paracetamol', 'Tylenol'),
('Paracetamol', 'Calpol'),
('Paracetamol', 'Anadin Paracetamol'),
('Paracetamol', 'Equate Paracetamol'),
('Paracetamol', 'Panasol'),
('Paracetamol', 'Apap'),
('Paracetamol', 'Paralgin'),
('Paracetamol', 'Paracetamol Sandoz'),
('Paracetamol', 'PainAway'),
('Diphenhydramine', 'Benadryl'),
('Loratadine', 'Claritin'),
('Cetirizine', 'Zyrtec'),
('Fexofenadine', 'Allegra'),
('Desloratadine', 'Clarinex'),
('Chlorpheniramine', 'Chlor-Trimeton'),
('Levocetirizine', 'Xyzal'),
('Promethazine', 'Phenergan'),
('Hydroxyzine', 'Atarax'),
('Dimetindene', 'Fenistil'),
('Dextromethorphan', 'Robitussin DM'),
('Guaifenesin', 'Mucinex'),
('Guaifenesin', 'Robitussin'),
('Diphenhydramine', 'Benadryl'),
('Bromhexine', 'Bisolvon'),
('Codeine', 'Tylenol with Codeine'),
('Honey and Lemon', 'Zarbee\'s Naturals'),
('Phenylephrine', 'Sudafed PE'),
('Carbocisteine', 'Mucodyne'),
('Carbocisteine', 'Solmux'),
('Chlorpheniramine', 'Chlor-Trimeton'),
('Ammonium Chloride', 'Bronchicum'),
('Acetaminophen', 'Tylenol'),
('Ibuprofen', 'Advil'),
('Iboprofen', 'Midol'),
('Iboprofen', 'Motrin'),
('Aspirin', 'Bayer Aspirin'),
('Naproxen', 'Aleve'),
('Diclofenac', 'Voltaren'),
('Tramadol', 'Ultram'),
('Morphine', 'MS Contin'),
('Hydrocodone', 'Vicodin'),
('Oxycodone', 'OxyContin'),
('Meloxicam', 'Mobic');

INSERT INTO lab_test_record (test_description)
VALUES
('Complete Blood Count'),
('Basic Metabolic Panel'),
('Comprehensive Metabolic Panel'),
('Lipid Profile'),
('Thyroid Function Test'),
('Blood Glucose Test'),
('Hemoglobin A1c'),
('Urinalysis'),
('Liver Function Test'),
('Kidney Function Test'),
('Electrolytes Test'),
('Prothrombin Time (PT)'),
('Partial Thromboplastin Time'),
('D-dimer Test'),
('C-reactive Protein'),
('Erythrocyte Sedimentation Rate'),
('Vitamin D Test'),
('Iron Studies'),
('B-type Natriuretic Peptide'),
('Troponin Test'),
('Creatine Kinase'),
('Amylase Test'),
('Lipase Test'),
('Sodium Test'),
('Potassium Test'),
('Calcium Test'),
('Magnesium Test'),
('Phosphate Test'),
('Complete Urine Culture'),
('Hepatitis B Surface Antigen Test'),
('Hepatitis C Test'),
('HIV Test'),
('Syphilis Test'),
('Blood Cultures'),
('Cholesterol Test'),
('Hemoglobin Test'),
('White Blood Cell Count'),
('Red Blood Cell Count'),
('Platelet Count'),
('Reticulocyte Count'),
('Arterial Blood Gas'),
('Pulmonary Function Test'),
('Spirometry'),
('Chest X-ray'),
('CT Scan'),
('MRI Scan'),
('Ultrasound'),
('Mammogram'),
('Pap Smear'),
('Prostate-Specific Antigen Test'),
('Biopsy'),
('Genetic Testing'),
('PCR Test for Infectious Diseases'),
('Allergy Test');

INSERT INTO medical_diagnosis_record (diagnosis_description)
VALUES
('Hypertension'),
('Diabetes Mellitus Type 2'),
('Acute Bronchitis'),
('Asthma'),
('Pneumonia'),
('Urinary Tract Infection (UTI)'),
('Gastroesophageal Reflux Disease (GERD)'),
('Chronic Obstructive Pulmonary Disease (COPD)'),
('Influenza (Flu)'),
('Hyperthyroidism'),
('Hypothyroidism'),
('Osteoarthritis'),
('Rheumatoid Arthritis'),
('Gout'),
('Migraine'),
('Gallstones (Cholelithiasis)'),
('Peptic Ulcer Disease'),
('Kidney Stones'),
('Acute Myocardial Infarction (Heart Attack)'),
('Congestive Heart Failure (CHF)'),
('Stroke (Cerebrovascular Accident)'),
('Cirrhosis of the Liver'),
('Anemia'),
('Hepatitis B'),
('HIV/AIDS'),
('Tuberculosis (TB)'),
('Parkinson\'s Disease'),
('Alzheimer\'s Disease'),
('Psoriasis'),
('Depression');

INSERT INTO chief_complaint_record (complaint_description)
VALUES
('Headaches'),
('Thirst'),
('Cough'),
('Wheezing'),
('Fever'),
('Painful Urination'),
('Heartburn'),
('Coughing'),
('Chills'),
('Weight Loss'),
('Fatigue'),
('Joint Pain'),
('Swollen Joints'),
('Toe Pain'),
('Headache'),
('Abdominal Pain'),
('Stomach Pain'),
('Flank Pain'),
('Chest Pain'),
('Shortness of Breath'),
('Weakness'),
('Jaundice'),
('Pallor'),
('Yellowing'),
('Weight Loss'),
('Cough'),
('Tremors'),
('Memory Loss'),
('Red Patches'),
('Sadness');
